#!/usr/bin/env bash
# Install Android SDK (API 35) into ~/Android/Sdk — no apt package for platform-35 on Ubuntu.
# Run once: bash scripts/setup_android_sdk.sh
set -euo pipefail

SDK_ROOT="${ANDROID_HOME:-$HOME/Android/Sdk}"
CMDTOOLS_ZIP_URL="${CMDTOOLS_ZIP_URL:-https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip}"
JAVA_CANDIDATES=(
  "${JAVA_HOME:-}"
  /usr/lib/jvm/java-17-openjdk-amd64
  /usr/lib/jvm/java-17-openjdk
)

pick_java() {
  local c
  for c in "${JAVA_CANDIDATES[@]}"; do
    [[ -z "$c" ]] && continue
    if [[ -x "$c/bin/java" ]]; then
      echo "$c"
      return 0
    fi
  done
  if command -v java >/dev/null 2>&1; then
    dirname "$(dirname "$(readlink -f "$(command -v java)")")"
    return 0
  fi
  return 1
}

JAVA_HOME_RESOLVED="$(pick_java)" || {
  echo "JDK 17 belum ada. Install dulu:" >&2
  echo "  sudo apt install -y openjdk-17-jdk" >&2
  exit 1
}
export JAVA_HOME="$JAVA_HOME_RESOLVED"
export PATH="$JAVA_HOME/bin:$PATH"

echo "JAVA_HOME=$JAVA_HOME"
echo "SDK_ROOT=$SDK_ROOT"

mkdir -p "$SDK_ROOT/cmdline-tools"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [[ ! -x "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]]; then
  echo "Downloading Android cmdline-tools…"
  curl -fsSL "$CMDTOOLS_ZIP_URL" -o "$TMP/cmdtools.zip"
  unzip -q "$TMP/cmdtools.zip" -d "$TMP"
  rm -rf "$SDK_ROOT/cmdline-tools/latest"
  # zip contains top-level "cmdline-tools/"
  mv "$TMP/cmdline-tools" "$SDK_ROOT/cmdline-tools/latest"
fi

SDKMANAGER="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
yes | "$SDKMANAGER" --sdk_root="$SDK_ROOT" --licenses >/tmp/android-sdk-licenses.log || true
"$SDKMANAGER" --sdk_root="$SDK_ROOT" \
  "platform-tools" \
  "platforms;android-35" \
  "build-tools;35.0.0"

# Point Gradle at this SDK
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cat >"$ROOT/android-agent/local.properties" <<EOF
## Generated by scripts/setup_android_sdk.sh — do not commit secrets here
sdk.dir=$SDK_ROOT
EOF

BASHRC="$HOME/.bashrc"
MARKER="# >>> siksik android sdk >>>"
if ! grep -qF "$MARKER" "$BASHRC" 2>/dev/null; then
  cat >>"$BASHRC" <<EOF

$MARKER
export JAVA_HOME=$JAVA_HOME
export ANDROID_HOME=$SDK_ROOT
export ANDROID_SDK_ROOT=\$ANDROID_HOME
export PATH="\$JAVA_HOME/bin:\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH"
# <<< siksik android sdk <<<
EOF
  echo "Appended ANDROID_HOME/JAVA_HOME to ~/.bashrc"
fi

export ANDROID_HOME="$SDK_ROOT"
export ANDROID_SDK_ROOT="$SDK_ROOT"
echo ""
echo "OK. Smoke-build agent:"
echo "  source ~/.bashrc"
echo "  cd $ROOT/android-agent && ./gradlew :app:assembleDebug :automation:assembleDebug"
